### ISSUE TITLE
Glitch text

### ISSUE THREAD

**Issue by NullByte75** [spicesouls/spice.net#1]
i downloaded spice net and runned the client (on windows) and some caracters are like this 
![Annotazione 2020-08-24 115527](https://user-images.githubusercontent.com/66488397/91031448-de2b7580-e600-11ea-91a1-c3445a719cbf.jpg)

**Comment by spicesouls** [comment]
They are _ANSI color codes_! This is partly because you are on windows, but I am aware there are workarounds that I can look into. These color codes do work in Unix terminals though. I'll try to debug it.

**Comment by spicesouls** [comment]
Update: I believe I have fixed this issue! I just had to add the Windows command `cls` to the beginning of the script!
